# Dependencies

highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Michael Angerman
tagline:          Angerman Resume
url:              http://stormasm.github.io
baseurl:          /link16/
author:
  name:           Michael Angerman
  url:            http://michaelangerman.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/stormasm/link16
